### ISSUE TITLE
RuntimeException raised when adding external Jar to the Soot classpath

### ISSUE THREAD

**Issue by hanyrax** [Sable/soot#1087] opened 2018-12-30 15:42 UTC
Having the Soot classpath set as following
`String classpath = "/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/jre/lib/jce.jar:/Users/blabla/Documents/projects/jars/jython-standalone-2.5.2.jar:/Users/blabla/Documents/projects/jars/commons-collections4-4.0.jar"`

Then
`Options.v().set_soot_classpath(classpath);`
`Scene.v().loadNecessaryClasses(); //The following RuntimeException is triggered by this call`

`Exception in thread "main" java.lang.RuntimeException: Attempt to create RefType containing a / --> /Users/blabla/Documents/projects/jars/commons-collections4-4.0.jar
	at soot.RefType.<init>(RefType.java:59)`

The exception seems to be independent from any specific jar in the classpath, in fact, swapping the last two jars in the classpath doesn't change the outcome of the exception which continues to refer to the last external (not under the JDK path) jar in the classpath anyway.

**Comment by mbenz89** [comment] 2019-01-16 22:35
Sorry, I cannot reproduce this error. Also, since you are only setting a classpath but no process dir (classes that should be analyzed), the call to `Scene.v().loadNecessaryClasses()` will basically do nothing but loading some very basic standard classes.
Classes in the classpath will only be considered if referenced by other classes (i.e. those found in the process dir).

Maybe you have some invalid characters in your original classpath?

**Comment by anddann** [comment] 2019-08-15 12:33
Since the thread starter did not respond, can we close the issue?

**Closed** 2019-08-15 13:53 UTC
