### ISSUE TITLE
java.lang.RuntimeException when using CFGViewer command line option

### ISSUE THREAD

**Issue by TealTulips** [Sable/soot#1313] opened 2020-03-13 17:32 UTC
Steps to reproduce:
1.) javac -d ./target/classes -cp ./soot-3.3.0.jar ./src/main/java/staticAnalysis/FindPrimeFactor.java
2.) java -cp /Users/xyz/eclipse-workspace/staticAnalysis/sootclasses_j9-trunk-jar-with-dependencies.jar soot.tools.CFGViewer -cp "." -pp --graph=BriefUnitGraph --ir=grimp -p jb use-original-names:true FindPrimeFactor

Files used to reproduce: 

import java.util.Arrays;
import java.util.List;

public class FindPrimeFactor {
   	public static void main(String []args) {
		
	    List<Integer>a= Arrays.asList(12, 25, 18, 8); //happy path
	    List<Integer> b = Arrays.asList(6, 2, 3, 2);
	   System.out.println("INDEX "+findPrimeFactor(a,b));

	}
	

    public static int findPrimeFactor(List<Integer> a, List<Integer> b) throws IllegalArgumentException{
    	   	
    	try {
    	    if (a == null) 
    	        throw new NullPointerException();
    	    }    	
    	catch(NullPointerException e) {
    		throw new IllegalArgumentException("List a cannot be null");
    	}
    	try {
    		if (b == null) 
    	        throw new NullPointerException();    	}
    	catch(NullPointerException e) {
    		throw new IllegalArgumentException("List b cannot be null");
    	}
        for(int i = 0; i < b.size() && i < a.size(); i++) {
        	if(a.get(i)==null||b.get(i)==null|| b.get(i).equals(0))
        	 i++;
        	if(isPrime(b.get(i)) == true && a.get(i) % b.get(i) == 0) {
                return i;
            }
        }
		throw new IllegalArgumentException("List b doesn't have prime factor of any element in list a.");

    }
   
    public static boolean isPrime(int num) {
	    int m,n,test=1;  
    	if(num==1){
		test=2;
		testFunc(test);
    		return false;
	}
	if(num<5){

		 m =6;
		 //return true;
	}
	else
	{	 n = 7;
	test =5;
		testFunc(test);
	
    	for(int i = 2; i < num; i++) {
            if(num % i == 0) {
                return false;
            }
        }}
        return true;
    }

    public static void testFunc(int test){
	    System.out.println("TEST HERE "+test);

    }
}

Soot version: <pre>sootclasses_j9-trunk</pre>

Command line:
<pre>-cp . -pp -p jtp.printcfg graph-type:BriefUnitGraph -p jtp.printcfg ir:grimp -p jb use-original-names:true FindPrimeFactor</pre>

Max Memory:
<pre>2048MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: Failed to convert &#60;FindPrimeFactor: void testFunc(int)&#62;
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2062)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:402)
	at soot.PackManager$1.run(PackManager.java:1279)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.RuntimeException: 
Aborting: can&#39;t find classfile java.lang.invoke.StringConcatFactory
	at soot.Scene.getSootClass(Scene.java:1182)
	at soot.asm.AsmMethodSource.getClassFromScene(AsmMethodSource.java:349)
	at soot.asm.AsmMethodSource.toSootMethodRef(AsmMethodSource.java:1502)
	at soot.asm.AsmMethodSource.convertInvokeDynamicInsn(AsmMethodSource.java:1399)
	at soot.asm.AsmMethodSource.convert(AsmMethodSource.java:1813)
	at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:2060)
	... 5 more
</pre>

**Comment by anddann** [comment] 2020-03-13 17:48
'sootclasses_j9-trunk-jar-with-dependencies.jar ' is deprecated can you please use https://repo1.maven.org/maven2/ca/mcgill/sable/soot/

**Comment by TealTulips** [comment] 2020-03-13 21:01
Thanks for the quick response. I started using soot-4.1.0.jar but I'm still getting the same error.

**Comment by anddann** [comment] 2020-03-13 21:09
the class `java.lang.invoke.StringConcatFactory` was introduced with Java 9, which version of Java do you use to execute Soot.

**Comment by anddann** [comment] 2020-03-13 21:36
Thx for reporting this issue. I've tested it in docker openjdk:11 and fixed the issue in #1314
and uploaded a new jar for testing here
https://drive.google.com/file/d/1rjTO5K05oFxwPqDXMCj3ir2Dgs41yX5X/view?usp=sharing

**Comment by TealTulips** [comment] 2020-03-13 22:08
I used 

> the class `java.lang.invoke.StringConcatFactory` was introduced with Java 9, which version of Java do you use to execute Soot.

I am using java version "9.0.4"

**Comment by TealTulips** [comment] 2020-03-13 22:12
I tried the jar you shared and this is the result.

java -cp /Users/xyz/eclipse-workspace/staticAnalysis/sootclasses-trunk-jar-with-dependencies.jar soot.tools.CFGViewer -cp "." -pp --graph=BriefUnitGraph --ir=grimp -p jb use-original-names:true FindPrimeFactor
Soot started on Fri Mar 13 18:10:33 EDT 2020
[Thread-5] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
java.lang.NullPointerException
	at soot.grimp.internal.GDynamicInvokeExpr.<init>(GDynamicInvokeExpr.java:57)
	at soot.grimp.Grimp.newDynamicInvokeExpr(Grimp.java:421)
	at soot.grimp.Grimp$1.caseDynamicInvokeExpr(Grimp.java:834)
	at soot.jimple.internal.JDynamicInvokeExpr.apply(JDynamicInvokeExpr.java:220)
	at soot.grimp.Grimp.newExpr(Grimp.java:716)
	at soot.grimp.GrimpBody.<init>(GrimpBody.java:185)
	at soot.grimp.Grimp.newBody(Grimp.java:891)
	at soot.util.cfgcmd.CFGIntermediateRep$3.getBody(CFGIntermediateRep.java:67)
	at soot.tools.CFGViewer.internalTransform(CFGViewer.java:83)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:120)
	at soot.BodyPack.internalApply(BodyPack.java:50)
	at soot.Pack.apply(Pack.java:125)
	at soot.PackManager.runBodyPacks(PackManager.java:1005)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:660)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Exception in thread "Thread-5" java.lang.NullPointerException
	at soot.grimp.internal.GDynamicInvokeExpr.<init>(GDynamicInvokeExpr.java:57)
	at soot.grimp.Grimp.newDynamicInvokeExpr(Grimp.java:421)
	at soot.grimp.Grimp$1.caseDynamicInvokeExpr(Grimp.java:834)
	at soot.jimple.internal.JDynamicInvokeExpr.apply(JDynamicInvokeExpr.java:220)
	at soot.grimp.Grimp.newExpr(Grimp.java:716)
	at soot.grimp.GrimpBody.<init>(GrimpBody.java:185)
	at soot.grimp.Grimp.newBody(Grimp.java:891)
	at soot.util.cfgcmd.CFGIntermediateRep$3.getBody(CFGIntermediateRep.java:67)
	at soot.tools.CFGViewer.internalTransform(CFGViewer.java:83)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:120)
	at soot.BodyPack.internalApply(BodyPack.java:50)
	at soot.Pack.apply(Pack.java:125)
	at soot.PackManager.runBodyPacks(PackManager.java:1005)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:660)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.NullPointerException
	at soot.grimp.internal.GDynamicInvokeExpr.<init>(GDynamicInvokeExpr.java:57)
	at soot.grimp.Grimp.newDynamicInvokeExpr(Grimp.java:421)
	at soot.grimp.Grimp$1.caseDynamicInvokeExpr(Grimp.java:834)
	at soot.jimple.internal.JDynamicInvokeExpr.apply(JDynamicInvokeExpr.java:220)
	at soot.grimp.Grimp.newExpr(Grimp.java:716)
	at soot.grimp.GrimpBody.<init>(GrimpBody.java:185)
	at soot.grimp.Grimp.newBody(Grimp.java:891)
	at soot.util.cfgcmd.CFGIntermediateRep$3.getBody(CFGIntermediateRep.java:67)
	at soot.tools.CFGViewer.internalTransform(CFGViewer.java:83)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:120)
	at soot.BodyPack.internalApply(BodyPack.java:50)
	at soot.Pack.apply(Pack.java:125)
	at soot.PackManager.runBodyPacks(PackManager.java:1005)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:660)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by anddann** [comment] 2020-03-13 22:16
Thx for reporting, I jsut quickly checked the normal soot process but not the CFGViewer
Maybe @mbenz89 can help us here.

**Comment by TealTulips** [comment] 2020-03-14 18:34
I am still having issues when running the command for CFGViewer with jdk 11

Soot started on Sat Mar 14 14:33:23 EDT 2020
[Thread-5] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
java.lang.NullPointerException
	at soot.grimp.internal.GDynamicInvokeExpr.<init>(GDynamicInvokeExpr.java:57)
	at soot.grimp.Grimp.newDynamicInvokeExpr(Grimp.java:421)
	at soot.grimp.Grimp$1.caseDynamicInvokeExpr(Grimp.java:834)
	at soot.jimple.internal.JDynamicInvokeExpr.apply(JDynamicInvokeExpr.java:220)
	at soot.grimp.Grimp.newExpr(Grimp.java:716)
	at soot.grimp.GrimpBody.<init>(GrimpBody.java:185)
	at soot.grimp.Grimp.newBody(Grimp.java:891)
	at soot.util.cfgcmd.CFGIntermediateRep$3.getBody(CFGIntermediateRep.java:67)
	at soot.tools.CFGViewer.internalTransform(CFGViewer.java:83)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:120)
	at soot.BodyPack.internalApply(BodyPack.java:50)
	at soot.Pack.apply(Pack.java:125)
	at soot.PackManager.runBodyPacks(PackManager.java:1005)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:660)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "Thread-5" java.lang.NullPointerException
	at soot.grimp.internal.GDynamicInvokeExpr.<init>(GDynamicInvokeExpr.java:57)
	at soot.grimp.Grimp.newDynamicInvokeExpr(Grimp.java:421)
	at soot.grimp.Grimp$1.caseDynamicInvokeExpr(Grimp.java:834)
	at soot.jimple.internal.JDynamicInvokeExpr.apply(JDynamicInvokeExpr.java:220)
	at soot.grimp.Grimp.newExpr(Grimp.java:716)
	at soot.grimp.GrimpBody.<init>(GrimpBody.java:185)
	at soot.grimp.Grimp.newBody(Grimp.java:891)
	at soot.util.cfgcmd.CFGIntermediateRep$3.getBody(CFGIntermediateRep.java:67)
	at soot.tools.CFGViewer.internalTransform(CFGViewer.java:83)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:120)
	at soot.BodyPack.internalApply(BodyPack.java:50)
	at soot.Pack.apply(Pack.java:125)
	at soot.PackManager.runBodyPacks(PackManager.java:1005)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:660)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.NullPointerException
	at soot.grimp.internal.GDynamicInvokeExpr.<init>(GDynamicInvokeExpr.java:57)
	at soot.grimp.Grimp.newDynamicInvokeExpr(Grimp.java:421)
	at soot.grimp.Grimp$1.caseDynamicInvokeExpr(Grimp.java:834)
	at soot.jimple.internal.JDynamicInvokeExpr.apply(JDynamicInvokeExpr.java:220)
	at soot.grimp.Grimp.newExpr(Grimp.java:716)
	at soot.grimp.GrimpBody.<init>(GrimpBody.java:185)
	at soot.grimp.Grimp.newBody(Grimp.java:891)
	at soot.util.cfgcmd.CFGIntermediateRep$3.getBody(CFGIntermediateRep.java:67)
	at soot.tools.CFGViewer.internalTransform(CFGViewer.java:83)
	at soot.BodyTransformer.transform(BodyTransformer.java:51)
	at soot.Transform.apply(Transform.java:120)
	at soot.BodyPack.internalApply(BodyPack.java:50)
	at soot.Pack.apply(Pack.java:125)
	at soot.PackManager.runBodyPacks(PackManager.java:1005)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:660)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by mbenz89** [comment] 2020-03-15 15:31
Might be related to https://github.com/Sable/soot/issues/1144 and https://github.com/Sable/soot/issues/1018 , while certainly looking a bit different.

@TealTulips could you debug your execution to pinpoint the cause of this NPE?

**Comment by TealTulips** [comment] 2020-03-16 19:59
There seems to be some problem when compiling java classes with soot jar. If compiled without soot e.g. through an IDE and then running the command line option for CFGViewer, it's working as expected. Tracking the stack trace of the issue led me to runBodyPacks method of PackManager class where it attempts to execute runBodyPacks on individual classes.

**Comment by mbenz89** [comment] 2020-04-25 13:34
fixed by #1315

**Closed by mbenz89** 2020-04-25 13:34 UTC
